OutDirCygwin:=$(shell cygpath -u "$(OutDir)")
IntDirCygwin:=$(shell cygpath -u "$(IntDir)")
all: $(OutDirCygwin)obj\global_intermediate\tools\json_schema_compiler\test\idl_object_types.cc $(OutDirCygwin)obj\global_intermediate\tools\json_schema_compiler\test\idl_basics.cc
	mkdir -p `cygpath -u "$(OutDir)obj\global_intermediate\tools\json_schema_compiler\test"`

$(OutDirCygwin)obj\global_intermediate\tools\json_schema_compiler\test\idl_object_types.cc $(OutDirCygwin)obj\global_intermediate\tools\json_schema_compiler\test\idl_object_types.h: ..\..\..\tools\json_schema_compiler\util_cc_helper.py ..\..\..\tools\json_schema_compiler\util.h ..\..\..\tools\json_schema_compiler\idl_schema.py ..\..\..\tools\json_schema_compiler\compiler.py ..\..\..\tools\json_schema_compiler\util.cc ..\..\..\tools\json_schema_compiler\cpp_util.py ..\..\..\tools\json_schema_compiler\cc_generator.py ..\..\..\tools\json_schema_compiler\h_generator.py ..\..\..\tools\json_schema_compiler\cpp_type_generator.py ..\..\..\tools\json_schema_compiler\any_helper.py ..\..\..\tools\json_schema_compiler\model.py idl_object_types.idl ..\..\..\tools\json_schema_compiler\code.py ..\..\..\tools\json_schema_compiler\any.cc ..\..\..\tools\json_schema_compiler\any.h
	"python" "../../../tools/json_schema_compiler/compiler.py" "idl_object_types.idl" "--root=../../.." "--destdir=$(OutDir)obj/global_intermediate" "--namespace=test::api"

$(OutDirCygwin)obj\global_intermediate\tools\json_schema_compiler\test\idl_basics.cc $(OutDirCygwin)obj\global_intermediate\tools\json_schema_compiler\test\idl_basics.h: ..\..\..\tools\json_schema_compiler\util_cc_helper.py ..\..\..\tools\json_schema_compiler\util.h ..\..\..\tools\json_schema_compiler\idl_schema.py ..\..\..\tools\json_schema_compiler\compiler.py idl_basics.idl ..\..\..\tools\json_schema_compiler\cpp_util.py ..\..\..\tools\json_schema_compiler\cc_generator.py ..\..\..\tools\json_schema_compiler\h_generator.py ..\..\..\tools\json_schema_compiler\cpp_type_generator.py ..\..\..\tools\json_schema_compiler\util.cc ..\..\..\tools\json_schema_compiler\any_helper.py ..\..\..\tools\json_schema_compiler\model.py ..\..\..\tools\json_schema_compiler\code.py ..\..\..\tools\json_schema_compiler\any.cc ..\..\..\tools\json_schema_compiler\any.h
	"python" "../../../tools/json_schema_compiler/compiler.py" "idl_basics.idl" "--root=../../.." "--destdir=$(OutDir)obj/global_intermediate" "--namespace=test::api"

