OutDirCygwin:=$(shell cygpath -u "$(OutDir)")
IntDirCygwin:=$(shell cygpath -u "$(IntDir)")
all: $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\media_galleries.h $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\experimental_bluetooth.h $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\file_system.h $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\experimental_idltest.cc $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\experimental_push_messaging.cc $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\app_runtime.cc $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\rtc_private.cc $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\experimental_usb.cc $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\downloads.cc $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\serial.cc $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\sync_file_system.cc $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\experimental_identity.cc $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\app_current_window_internal.h $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\experimental_discovery.h $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\media_galleries_private.cc $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\experimental_dns.cc $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\socket.cc $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\experimental_system_info_cpu.cc $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\experimental_system_info_storage.h $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\experimental_media_galleries.cc $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\app_window.cc $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\alarms.h
	mkdir -p `cygpath -u "$(OutDir)obj\global_intermediate\chrome\common\extensions\api"`

$(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\media_galleries.h $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\media_galleries.cc: ..\..\..\..\tools\json_schema_compiler\model.py ..\..\..\..\tools\json_schema_compiler\util_cc_helper.py media_galleries.idl ..\..\..\..\tools\json_schema_compiler\cpp_util.py ..\..\..\..\tools\json_schema_compiler\h_generator.py ..\..\..\..\tools\json_schema_compiler\any_helper.py ..\..\..\..\tools\json_schema_compiler\cpp_type_generator.py ..\..\..\..\tools\json_schema_compiler\any.cc ..\..\..\..\tools\json_schema_compiler\any.h ..\..\..\..\tools\json_schema_compiler\code.py ..\..\..\..\tools\json_schema_compiler\util.h ..\..\..\..\tools\json_schema_compiler\compiler.py ..\..\..\..\tools\json_schema_compiler\idl_schema.py ..\..\..\..\tools\json_schema_compiler\util.cc ..\..\..\..\tools\json_schema_compiler\cc_generator.py
	"python" "../../../../tools/json_schema_compiler/compiler.py" "media_galleries.idl" "--root=../../../.." "--destdir=$(OutDir)obj/global_intermediate" "--namespace=extensions::api"

$(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\experimental_bluetooth.h $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\experimental_bluetooth.cc: ..\..\..\..\tools\json_schema_compiler\model.py ..\..\..\..\tools\json_schema_compiler\util_cc_helper.py ..\..\..\..\tools\json_schema_compiler\any.h experimental_bluetooth.idl ..\..\..\..\tools\json_schema_compiler\h_generator.py ..\..\..\..\tools\json_schema_compiler\any_helper.py ..\..\..\..\tools\json_schema_compiler\cpp_type_generator.py ..\..\..\..\tools\json_schema_compiler\any.cc ..\..\..\..\tools\json_schema_compiler\code.py ..\..\..\..\tools\json_schema_compiler\util.h ..\..\..\..\tools\json_schema_compiler\compiler.py ..\..\..\..\tools\json_schema_compiler\cpp_util.py ..\..\..\..\tools\json_schema_compiler\idl_schema.py ..\..\..\..\tools\json_schema_compiler\util.cc ..\..\..\..\tools\json_schema_compiler\cc_generator.py
	"python" "../../../../tools/json_schema_compiler/compiler.py" "experimental_bluetooth.idl" "--root=../../../.." "--destdir=$(OutDir)obj/global_intermediate" "--namespace=extensions::api"

$(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\file_system.h $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\file_system.cc: ..\..\..\..\tools\json_schema_compiler\model.py ..\..\..\..\tools\json_schema_compiler\util_cc_helper.py ..\..\..\..\tools\json_schema_compiler\code.py ..\..\..\..\tools\json_schema_compiler\cpp_util.py ..\..\..\..\tools\json_schema_compiler\h_generator.py ..\..\..\..\tools\json_schema_compiler\any_helper.py ..\..\..\..\tools\json_schema_compiler\cpp_type_generator.py file_system.idl ..\..\..\..\tools\json_schema_compiler\any.h ..\..\..\..\tools\json_schema_compiler\util.cc ..\..\..\..\tools\json_schema_compiler\util.h ..\..\..\..\tools\json_schema_compiler\compiler.py ..\..\..\..\tools\json_schema_compiler\idl_schema.py ..\..\..\..\tools\json_schema_compiler\any.cc ..\..\..\..\tools\json_schema_compiler\cc_generator.py
	"python" "../../../../tools/json_schema_compiler/compiler.py" "file_system.idl" "--root=../../../.." "--destdir=$(OutDir)obj/global_intermediate" "--namespace=extensions::api"

$(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\experimental_idltest.cc $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\experimental_idltest.h: ..\..\..\..\tools\json_schema_compiler\model.py ..\..\..\..\tools\json_schema_compiler\util_cc_helper.py ..\..\..\..\tools\json_schema_compiler\code.py ..\..\..\..\tools\json_schema_compiler\cpp_util.py ..\..\..\..\tools\json_schema_compiler\h_generator.py ..\..\..\..\tools\json_schema_compiler\any_helper.py ..\..\..\..\tools\json_schema_compiler\cpp_type_generator.py ..\..\..\..\tools\json_schema_compiler\any.cc ..\..\..\..\tools\json_schema_compiler\any.h experimental_idltest.idl ..\..\..\..\tools\json_schema_compiler\util.h ..\..\..\..\tools\json_schema_compiler\compiler.py ..\..\..\..\tools\json_schema_compiler\idl_schema.py ..\..\..\..\tools\json_schema_compiler\util.cc ..\..\..\..\tools\json_schema_compiler\cc_generator.py
	"python" "../../../../tools/json_schema_compiler/compiler.py" "experimental_idltest.idl" "--root=../../../.." "--destdir=$(OutDir)obj/global_intermediate" "--namespace=extensions::api"

$(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\experimental_push_messaging.cc $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\experimental_push_messaging.h: ..\..\..\..\tools\json_schema_compiler\model.py ..\..\..\..\tools\json_schema_compiler\util_cc_helper.py ..\..\..\..\tools\json_schema_compiler\any.h ..\..\..\..\tools\json_schema_compiler\cpp_util.py ..\..\..\..\tools\json_schema_compiler\h_generator.py ..\..\..\..\tools\json_schema_compiler\any_helper.py ..\..\..\..\tools\json_schema_compiler\cpp_type_generator.py ..\..\..\..\tools\json_schema_compiler\any.cc ..\..\..\..\tools\json_schema_compiler\code.py experimental_push_messaging.idl ..\..\..\..\tools\json_schema_compiler\util.h ..\..\..\..\tools\json_schema_compiler\compiler.py ..\..\..\..\tools\json_schema_compiler\idl_schema.py ..\..\..\..\tools\json_schema_compiler\util.cc ..\..\..\..\tools\json_schema_compiler\cc_generator.py
	"python" "../../../../tools/json_schema_compiler/compiler.py" "experimental_push_messaging.idl" "--root=../../../.." "--destdir=$(OutDir)obj/global_intermediate" "--namespace=extensions::api"

$(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\app_runtime.cc $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\app_runtime.h: ..\..\..\..\tools\json_schema_compiler\model.py ..\..\..\..\tools\json_schema_compiler\util_cc_helper.py ..\..\..\..\tools\json_schema_compiler\any.h app_runtime.idl ..\..\..\..\tools\json_schema_compiler\h_generator.py ..\..\..\..\tools\json_schema_compiler\any_helper.py ..\..\..\..\tools\json_schema_compiler\cpp_type_generator.py ..\..\..\..\tools\json_schema_compiler\any.cc ..\..\..\..\tools\json_schema_compiler\code.py ..\..\..\..\tools\json_schema_compiler\util.h ..\..\..\..\tools\json_schema_compiler\compiler.py ..\..\..\..\tools\json_schema_compiler\cpp_util.py ..\..\..\..\tools\json_schema_compiler\idl_schema.py ..\..\..\..\tools\json_schema_compiler\util.cc ..\..\..\..\tools\json_schema_compiler\cc_generator.py
	"python" "../../../../tools/json_schema_compiler/compiler.py" "app_runtime.idl" "--root=../../../.." "--destdir=$(OutDir)obj/global_intermediate" "--namespace=extensions::api"

$(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\rtc_private.cc $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\rtc_private.h: ..\..\..\..\tools\json_schema_compiler\model.py rtc_private.idl ..\..\..\..\tools\json_schema_compiler\code.py ..\..\..\..\tools\json_schema_compiler\cpp_util.py ..\..\..\..\tools\json_schema_compiler\h_generator.py ..\..\..\..\tools\json_schema_compiler\any_helper.py ..\..\..\..\tools\json_schema_compiler\cpp_type_generator.py ..\..\..\..\tools\json_schema_compiler\any.cc ..\..\..\..\tools\json_schema_compiler\any.h ..\..\..\..\tools\json_schema_compiler\util_cc_helper.py ..\..\..\..\tools\json_schema_compiler\util.h ..\..\..\..\tools\json_schema_compiler\compiler.py ..\..\..\..\tools\json_schema_compiler\idl_schema.py ..\..\..\..\tools\json_schema_compiler\util.cc ..\..\..\..\tools\json_schema_compiler\cc_generator.py
	"python" "../../../../tools/json_schema_compiler/compiler.py" "rtc_private.idl" "--root=../../../.." "--destdir=$(OutDir)obj/global_intermediate" "--namespace=extensions::api"

$(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\experimental_usb.cc $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\experimental_usb.h: ..\..\..\..\tools\json_schema_compiler\model.py ..\..\..\..\tools\json_schema_compiler\util_cc_helper.py ..\..\..\..\tools\json_schema_compiler\code.py ..\..\..\..\tools\json_schema_compiler\cpp_util.py ..\..\..\..\tools\json_schema_compiler\h_generator.py ..\..\..\..\tools\json_schema_compiler\any_helper.py ..\..\..\..\tools\json_schema_compiler\cpp_type_generator.py experimental_usb.idl ..\..\..\..\tools\json_schema_compiler\any.h ..\..\..\..\tools\json_schema_compiler\util.cc ..\..\..\..\tools\json_schema_compiler\util.h ..\..\..\..\tools\json_schema_compiler\compiler.py ..\..\..\..\tools\json_schema_compiler\idl_schema.py ..\..\..\..\tools\json_schema_compiler\any.cc ..\..\..\..\tools\json_schema_compiler\cc_generator.py
	"python" "../../../../tools/json_schema_compiler/compiler.py" "experimental_usb.idl" "--root=../../../.." "--destdir=$(OutDir)obj/global_intermediate" "--namespace=extensions::api"

$(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\downloads.cc $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\downloads.h: ..\..\..\..\tools\json_schema_compiler\model.py ..\..\..\..\tools\json_schema_compiler\util_cc_helper.py ..\..\..\..\tools\json_schema_compiler\code.py ..\..\..\..\tools\json_schema_compiler\cpp_util.py ..\..\..\..\tools\json_schema_compiler\h_generator.py ..\..\..\..\tools\json_schema_compiler\any_helper.py ..\..\..\..\tools\json_schema_compiler\cpp_type_generator.py ..\..\..\..\tools\json_schema_compiler\any.cc ..\..\..\..\tools\json_schema_compiler\any.h downloads.idl ..\..\..\..\tools\json_schema_compiler\util.h ..\..\..\..\tools\json_schema_compiler\compiler.py ..\..\..\..\tools\json_schema_compiler\idl_schema.py ..\..\..\..\tools\json_schema_compiler\util.cc ..\..\..\..\tools\json_schema_compiler\cc_generator.py
	"python" "../../../../tools/json_schema_compiler/compiler.py" "downloads.idl" "--root=../../../.." "--destdir=$(OutDir)obj/global_intermediate" "--namespace=extensions::api"

$(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\serial.cc $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\serial.h: ..\..\..\..\tools\json_schema_compiler\model.py ..\..\..\..\tools\json_schema_compiler\util_cc_helper.py ..\..\..\..\tools\json_schema_compiler\code.py ..\..\..\..\tools\json_schema_compiler\cpp_util.py ..\..\..\..\tools\json_schema_compiler\h_generator.py ..\..\..\..\tools\json_schema_compiler\any_helper.py ..\..\..\..\tools\json_schema_compiler\cpp_type_generator.py ..\..\..\..\tools\json_schema_compiler\any.cc ..\..\..\..\tools\json_schema_compiler\any.h serial.idl ..\..\..\..\tools\json_schema_compiler\util.h ..\..\..\..\tools\json_schema_compiler\compiler.py ..\..\..\..\tools\json_schema_compiler\idl_schema.py ..\..\..\..\tools\json_schema_compiler\util.cc ..\..\..\..\tools\json_schema_compiler\cc_generator.py
	"python" "../../../../tools/json_schema_compiler/compiler.py" "serial.idl" "--root=../../../.." "--destdir=$(OutDir)obj/global_intermediate" "--namespace=extensions::api"

$(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\sync_file_system.cc $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\sync_file_system.h: ..\..\..\..\tools\json_schema_compiler\model.py ..\..\..\..\tools\json_schema_compiler\util_cc_helper.py ..\..\..\..\tools\json_schema_compiler\code.py ..\..\..\..\tools\json_schema_compiler\cpp_util.py sync_file_system.idl ..\..\..\..\tools\json_schema_compiler\any_helper.py ..\..\..\..\tools\json_schema_compiler\cpp_type_generator.py ..\..\..\..\tools\json_schema_compiler\any.cc ..\..\..\..\tools\json_schema_compiler\any.h ..\..\..\..\tools\json_schema_compiler\util.h ..\..\..\..\tools\json_schema_compiler\compiler.py ..\..\..\..\tools\json_schema_compiler\idl_schema.py ..\..\..\..\tools\json_schema_compiler\util.cc ..\..\..\..\tools\json_schema_compiler\cc_generator.py ..\..\..\..\tools\json_schema_compiler\h_generator.py
	"python" "../../../../tools/json_schema_compiler/compiler.py" "sync_file_system.idl" "--root=../../../.." "--destdir=$(OutDir)obj/global_intermediate" "--namespace=extensions::api"

$(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\experimental_identity.cc $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\experimental_identity.h: ..\..\..\..\tools\json_schema_compiler\model.py experimental_identity.idl ..\..\..\..\tools\json_schema_compiler\code.py ..\..\..\..\tools\json_schema_compiler\cpp_util.py ..\..\..\..\tools\json_schema_compiler\h_generator.py ..\..\..\..\tools\json_schema_compiler\any_helper.py ..\..\..\..\tools\json_schema_compiler\cpp_type_generator.py ..\..\..\..\tools\json_schema_compiler\any.cc ..\..\..\..\tools\json_schema_compiler\any.h ..\..\..\..\tools\json_schema_compiler\util_cc_helper.py ..\..\..\..\tools\json_schema_compiler\util.h ..\..\..\..\tools\json_schema_compiler\compiler.py ..\..\..\..\tools\json_schema_compiler\idl_schema.py ..\..\..\..\tools\json_schema_compiler\util.cc ..\..\..\..\tools\json_schema_compiler\cc_generator.py
	"python" "../../../../tools/json_schema_compiler/compiler.py" "experimental_identity.idl" "--root=../../../.." "--destdir=$(OutDir)obj/global_intermediate" "--namespace=extensions::api"

$(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\app_current_window_internal.h $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\app_current_window_internal.cc: ..\..\..\..\tools\json_schema_compiler\model.py ..\..\..\..\tools\json_schema_compiler\util_cc_helper.py ..\..\..\..\tools\json_schema_compiler\code.py ..\..\..\..\tools\json_schema_compiler\cpp_util.py ..\..\..\..\tools\json_schema_compiler\h_generator.py ..\..\..\..\tools\json_schema_compiler\any_helper.py ..\..\..\..\tools\json_schema_compiler\cpp_type_generator.py app_current_window_internal.idl ..\..\..\..\tools\json_schema_compiler\any.h ..\..\..\..\tools\json_schema_compiler\util.cc ..\..\..\..\tools\json_schema_compiler\util.h ..\..\..\..\tools\json_schema_compiler\compiler.py ..\..\..\..\tools\json_schema_compiler\idl_schema.py ..\..\..\..\tools\json_schema_compiler\any.cc ..\..\..\..\tools\json_schema_compiler\cc_generator.py
	"python" "../../../../tools/json_schema_compiler/compiler.py" "app_current_window_internal.idl" "--root=../../../.." "--destdir=$(OutDir)obj/global_intermediate" "--namespace=extensions::api"

$(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\experimental_discovery.h $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\experimental_discovery.cc: ..\..\..\..\tools\json_schema_compiler\model.py ..\..\..\..\tools\json_schema_compiler\util_cc_helper.py ..\..\..\..\tools\json_schema_compiler\any.h ..\..\..\..\tools\json_schema_compiler\cpp_util.py ..\..\..\..\tools\json_schema_compiler\h_generator.py ..\..\..\..\tools\json_schema_compiler\any_helper.py ..\..\..\..\tools\json_schema_compiler\cpp_type_generator.py ..\..\..\..\tools\json_schema_compiler\any.cc ..\..\..\..\tools\json_schema_compiler\code.py experimental_discovery.idl ..\..\..\..\tools\json_schema_compiler\util.h ..\..\..\..\tools\json_schema_compiler\compiler.py ..\..\..\..\tools\json_schema_compiler\idl_schema.py ..\..\..\..\tools\json_schema_compiler\util.cc ..\..\..\..\tools\json_schema_compiler\cc_generator.py
	"python" "../../../../tools/json_schema_compiler/compiler.py" "experimental_discovery.idl" "--root=../../../.." "--destdir=$(OutDir)obj/global_intermediate" "--namespace=extensions::api"

$(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\media_galleries_private.cc $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\media_galleries_private.h: ..\..\..\..\tools\json_schema_compiler\model.py ..\..\..\..\tools\json_schema_compiler\util_cc_helper.py ..\..\..\..\tools\json_schema_compiler\code.py ..\..\..\..\tools\json_schema_compiler\cpp_util.py ..\..\..\..\tools\json_schema_compiler\h_generator.py ..\..\..\..\tools\json_schema_compiler\any_helper.py ..\..\..\..\tools\json_schema_compiler\cpp_type_generator.py ..\..\..\..\tools\json_schema_compiler\any.cc ..\..\..\..\tools\json_schema_compiler\any.h media_galleries_private.idl ..\..\..\..\tools\json_schema_compiler\util.h ..\..\..\..\tools\json_schema_compiler\compiler.py ..\..\..\..\tools\json_schema_compiler\idl_schema.py ..\..\..\..\tools\json_schema_compiler\util.cc ..\..\..\..\tools\json_schema_compiler\cc_generator.py
	"python" "../../../../tools/json_schema_compiler/compiler.py" "media_galleries_private.idl" "--root=../../../.." "--destdir=$(OutDir)obj/global_intermediate" "--namespace=extensions::api"

$(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\experimental_dns.cc $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\experimental_dns.h: ..\..\..\..\tools\json_schema_compiler\model.py ..\..\..\..\tools\json_schema_compiler\util_cc_helper.py ..\..\..\..\tools\json_schema_compiler\code.py ..\..\..\..\tools\json_schema_compiler\cpp_util.py ..\..\..\..\tools\json_schema_compiler\h_generator.py ..\..\..\..\tools\json_schema_compiler\any_helper.py ..\..\..\..\tools\json_schema_compiler\cpp_type_generator.py ..\..\..\..\tools\json_schema_compiler\any.cc ..\..\..\..\tools\json_schema_compiler\any.h experimental_dns.idl ..\..\..\..\tools\json_schema_compiler\util.h ..\..\..\..\tools\json_schema_compiler\compiler.py ..\..\..\..\tools\json_schema_compiler\idl_schema.py ..\..\..\..\tools\json_schema_compiler\util.cc ..\..\..\..\tools\json_schema_compiler\cc_generator.py
	"python" "../../../../tools/json_schema_compiler/compiler.py" "experimental_dns.idl" "--root=../../../.." "--destdir=$(OutDir)obj/global_intermediate" "--namespace=extensions::api"

$(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\socket.cc $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\socket.h: ..\..\..\..\tools\json_schema_compiler\model.py ..\..\..\..\tools\json_schema_compiler\util_cc_helper.py ..\..\..\..\tools\json_schema_compiler\code.py ..\..\..\..\tools\json_schema_compiler\cpp_util.py ..\..\..\..\tools\json_schema_compiler\h_generator.py ..\..\..\..\tools\json_schema_compiler\util.h ..\..\..\..\tools\json_schema_compiler\any_helper.py ..\..\..\..\tools\json_schema_compiler\cpp_type_generator.py ..\..\..\..\tools\json_schema_compiler\any.cc ..\..\..\..\tools\json_schema_compiler\any.h socket.idl ..\..\..\..\tools\json_schema_compiler\compiler.py ..\..\..\..\tools\json_schema_compiler\idl_schema.py ..\..\..\..\tools\json_schema_compiler\util.cc ..\..\..\..\tools\json_schema_compiler\cc_generator.py
	"python" "../../../../tools/json_schema_compiler/compiler.py" "socket.idl" "--root=../../../.." "--destdir=$(OutDir)obj/global_intermediate" "--namespace=extensions::api"

$(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\experimental_system_info_cpu.cc $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\experimental_system_info_cpu.h: ..\..\..\..\tools\json_schema_compiler\model.py experimental_system_info_cpu.idl ..\..\..\..\tools\json_schema_compiler\code.py ..\..\..\..\tools\json_schema_compiler\cpp_util.py ..\..\..\..\tools\json_schema_compiler\h_generator.py ..\..\..\..\tools\json_schema_compiler\any_helper.py ..\..\..\..\tools\json_schema_compiler\cpp_type_generator.py ..\..\..\..\tools\json_schema_compiler\any.cc ..\..\..\..\tools\json_schema_compiler\any.h ..\..\..\..\tools\json_schema_compiler\util_cc_helper.py ..\..\..\..\tools\json_schema_compiler\util.h ..\..\..\..\tools\json_schema_compiler\compiler.py ..\..\..\..\tools\json_schema_compiler\idl_schema.py ..\..\..\..\tools\json_schema_compiler\util.cc ..\..\..\..\tools\json_schema_compiler\cc_generator.py
	"python" "../../../../tools/json_schema_compiler/compiler.py" "experimental_system_info_cpu.idl" "--root=../../../.." "--destdir=$(OutDir)obj/global_intermediate" "--namespace=extensions::api"

$(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\experimental_system_info_storage.h $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\experimental_system_info_storage.cc: ..\..\..\..\tools\json_schema_compiler\model.py ..\..\..\..\tools\json_schema_compiler\util_cc_helper.py ..\..\..\..\tools\json_schema_compiler\any.h experimental_system_info_storage.idl ..\..\..\..\tools\json_schema_compiler\h_generator.py ..\..\..\..\tools\json_schema_compiler\any_helper.py ..\..\..\..\tools\json_schema_compiler\cpp_type_generator.py ..\..\..\..\tools\json_schema_compiler\any.cc ..\..\..\..\tools\json_schema_compiler\code.py ..\..\..\..\tools\json_schema_compiler\util.h ..\..\..\..\tools\json_schema_compiler\compiler.py ..\..\..\..\tools\json_schema_compiler\cpp_util.py ..\..\..\..\tools\json_schema_compiler\idl_schema.py ..\..\..\..\tools\json_schema_compiler\util.cc ..\..\..\..\tools\json_schema_compiler\cc_generator.py
	"python" "../../../../tools/json_schema_compiler/compiler.py" "experimental_system_info_storage.idl" "--root=../../../.." "--destdir=$(OutDir)obj/global_intermediate" "--namespace=extensions::api"

$(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\experimental_media_galleries.cc $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\experimental_media_galleries.h: ..\..\..\..\tools\json_schema_compiler\model.py ..\..\..\..\tools\json_schema_compiler\util_cc_helper.py ..\..\..\..\tools\json_schema_compiler\code.py ..\..\..\..\tools\json_schema_compiler\cpp_util.py ..\..\..\..\tools\json_schema_compiler\h_generator.py ..\..\..\..\tools\json_schema_compiler\any_helper.py ..\..\..\..\tools\json_schema_compiler\cpp_type_generator.py ..\..\..\..\tools\json_schema_compiler\any.cc ..\..\..\..\tools\json_schema_compiler\any.h ..\..\..\..\tools\json_schema_compiler\util.h ..\..\..\..\tools\json_schema_compiler\compiler.py ..\..\..\..\tools\json_schema_compiler\idl_schema.py ..\..\..\..\tools\json_schema_compiler\util.cc ..\..\..\..\tools\json_schema_compiler\cc_generator.py experimental_media_galleries.idl
	"python" "../../../../tools/json_schema_compiler/compiler.py" "experimental_media_galleries.idl" "--root=../../../.." "--destdir=$(OutDir)obj/global_intermediate" "--namespace=extensions::api"

$(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\app_window.cc $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\app_window.h: ..\..\..\..\tools\json_schema_compiler\model.py ..\..\..\..\tools\json_schema_compiler\util_cc_helper.py ..\..\..\..\tools\json_schema_compiler\code.py ..\..\..\..\tools\json_schema_compiler\cpp_util.py ..\..\..\..\tools\json_schema_compiler\h_generator.py ..\..\..\..\tools\json_schema_compiler\any_helper.py ..\..\..\..\tools\json_schema_compiler\cpp_type_generator.py ..\..\..\..\tools\json_schema_compiler\any.cc ..\..\..\..\tools\json_schema_compiler\any.h app_window.idl ..\..\..\..\tools\json_schema_compiler\util.h ..\..\..\..\tools\json_schema_compiler\compiler.py ..\..\..\..\tools\json_schema_compiler\idl_schema.py ..\..\..\..\tools\json_schema_compiler\util.cc ..\..\..\..\tools\json_schema_compiler\cc_generator.py
	"python" "../../../../tools/json_schema_compiler/compiler.py" "app_window.idl" "--root=../../../.." "--destdir=$(OutDir)obj/global_intermediate" "--namespace=extensions::api"

$(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\alarms.h $(OutDirCygwin)obj\global_intermediate\chrome\common\extensions\api\alarms.cc: ..\..\..\..\tools\json_schema_compiler\model.py ..\..\..\..\tools\json_schema_compiler\util_cc_helper.py ..\..\..\..\tools\json_schema_compiler\code.py ..\..\..\..\tools\json_schema_compiler\cpp_util.py ..\..\..\..\tools\json_schema_compiler\h_generator.py ..\..\..\..\tools\json_schema_compiler\any_helper.py ..\..\..\..\tools\json_schema_compiler\cpp_type_generator.py ..\..\..\..\tools\json_schema_compiler\any.cc ..\..\..\..\tools\json_schema_compiler\any.h ..\..\..\..\tools\json_schema_compiler\compiler.py ..\..\..\..\tools\json_schema_compiler\util.h alarms.idl ..\..\..\..\tools\json_schema_compiler\idl_schema.py ..\..\..\..\tools\json_schema_compiler\util.cc ..\..\..\..\tools\json_schema_compiler\cc_generator.py
	"python" "../../../../tools/json_schema_compiler/compiler.py" "alarms.idl" "--root=../../../.." "--destdir=$(OutDir)obj/global_intermediate" "--namespace=extensions::api"

